### ISSUE TITLE
Test name Test_dates

### ISSUE THREAD

**Issue by lisavalexander** [heroldn/climpact2#20]
Tests that dates/times follow a standard format e.g. time order and monotonically increasing

**Comment by tammasloughran** [comment]
This test isn't really relevant to netCDF files because the netCDF library will prevent definition of a dimension variable that isn’t monotonic.
But this could happen in ASCII files. I swapped two of the records in the Bathurst file and loaded it into climpact2. The QC doesn't seem to make any mention that the swapped dates where in the wrong order. A few QC errors were found but none of them were associated with the dates I had messed with.
The standard output did throw some warnings but nothing to do with dates it seems:
```
[1] "CHECKING FOR TEMPERATURE OUTLIERS."
[1] "CALCULATING MEANS AND STANDARD DEVIATIONS..."
[1] "TESTING DATA, PLEASE WAIT..."
Warning in merge.data.frame(z, x, by = "id", all.x = F, all.y = T) :
  column names ‘NA’, ‘NA’, ‘NA’, ‘NA’ are duplicated in the result
Warning in merge.data.frame(z, x, by = "id", all.x = F, all.y = T) :
  column names ‘NA’, ‘NA’, ‘NA’, ‘NA’ are duplicated in the result
[1] "COMPLETED CHECKING FOR TEMPERATURE OUTLIERS."
```

**Comment by tammasloughran** [comment]
Also, It would be nice for the QC to give some sort of indication when it's finished doing everything. Is checking for temp outliers everything that it does?

**Comment by heroldn** [comment]
Hi Tammas, dates are checked now for order, will tell you when a new
version is on git.

Cheers

PS. I am trying to have a message or hourglass icon going when the long
calculation is being done too.
