### ISSUE TITLE
Test name Too_many_zeros

### ISSUE THREAD

**Issue by lisavalexander** [heroldn/climpact2#28]
Tests the possibility that missing data have been keyed as zero

**Comment by tammasloughran** [comment]
I entered a period of 0 values in the Bathurst example file. The QC can identify bad temp data that has been keyed as 0 only if both tmax and tmin are 0. If only tmin is 0 it does not since 0 is not an unusual value. So this is merely the check that tmax is greater than tmin. Since it would be very unusual to have consecutive days of 0 values, there should be a check for this.

**Comment by heroldn** [comment]
Done. Warning generated.
