### ISSUE TITLE
Missing dependencies

### ISSUE THREAD

**Issue by taerwin** [heroldn/climpact2#33]
Packages caTools and Rcpp need to be added to the dependency list. 

On running climpact2.checker package climdex.pcic fails with the following error:

ERROR: dependencies ‘caTools’, ‘Rcpp’ are not available for package ‘climdex.pcic’
* removing ‘Rpackages/climdex.pcic’

Also ncdf4 package requires the netcdf header files or compilation will fail.

**Comment by heroldn** [comment]
Thanks, I've added those in. Keep in mind that for now you need to install the version of climdex.pcic that comes with this package. climpact2.checker will install this but it won't uninstall an existing climdex.pcic package. So if climdex.pcic is already installed you need to manually remove it (otherwise some of the percentile indices won't work).
