### ISSUE TITLE
Specifying multiple indices

### ISSUE THREAD

**Issue by tammasloughran** [heroldn/climpact2#4]
It seems that specifying multiple indices does not work. For example I tried:
```
indices=c("hw","fd","fd2","fdm2","fdm20","id","su","tr","gsl","txx","tnn","tnx","txn","dtr",
"wsdi","wsdin","csdi","csdin","tx50p","tx95t","tx10p","tx90p","tn10p","tn90p","tm5a",
"tm5b","tm10a","tm10b","su30","su35","hddheat","cddcold","gddgrow","ntxntn","ntxbntnb")
```
It will calculate the first one "hw" but ignore the others. Or at least it only saves the first one to file. (N.B. hw also takes ages to calculate. >2 hours for 50 years of awap at 0.5deg resolution) I've tried other combinations. It's always only the first index. It doesn't matter which index it is.
I used climpact2_0.3.r

**Comment by heroldn** [comment]
Hi Tammas. I think I left a piece of code in there accidentally that only went through the first index. I've just changed the line I think is the problem. Can you get climpact2_0.3.r again and see if it works.

And yes, the package will be slow, especially for "hw" as it's calculating about 15 indices in one. If you specify all indices (can do this by just saying "all") then it will take about 3 days!
I'd avoid calculating "hw" at the moment anyway, as I've changed it since. Will hopefully upload a new file at the end of the week.

**Comment by tammasloughran** [comment]
Okay, that seems to have fixed it. Thanks Nick!
