### ISSUE TITLE
Test #7: Incorrect units

### ISSUE THREAD

**Issue by tammasloughran** [heroldn/climpact2#8]
Some indices do not have the correct units. Here is a list of units that are faulty and then what they should be.

```
1,4c1,4
< 		fd:units = "days" ;
< 		fd2:units = "days" ;
< 		fdm2:units = "days" ;
< 		fdm20:units = "days" ;
---
> 		fd:units = "degC" ;
> 		fd2:units = "degC" ;
> 		fdm2:units = "degC" ;
> 		fdm20:units = "degC" ;
31,35c31,35
< 		hddheat:units = "degC" ;
< 		cddcold:units = "degC" ;
< 		gddgrow:units = "degC" ;
< 		ntxntn:units = "events" ;
< 		ntxbntnb:units = "events" ;
---
> 		hddheat:units = "days" ;
> 		cddcold:units = "days" ;
> 		gddgrow:units = "days" ;
> 		ntxntn:units = "days" ;
> 		ntxbntnb:units = "days" ;
38,39c38,39
< 		cwd:units = "days" ;
< 		r10mm:units = "days" ;
---
> 		cwd:units = "degC" ;
> 		r10mm:units = "degC" ;
41,48c41,47
< 		rx1day:units = "mm" ;
< 		rx5day:units = "mm" ;
< 		prcptot:units = "mm" ;
< 		sdii:units = "mm/day" ;
< 		r95ptot:units = "%" ;
< 		r99ptot:units = "%" ;
< 		rxnday:units = "mm" ;
< 		rnnmm:units = "days" ;
---
> 		rx1day:units = "days" ;
> 		prcptot:units = "days" ;
> 		sdii:units = "degC" ;
> 		r95ptot:units = "degC" ;
> 		r99ptot:units = "degC" ;
> 		rxnday:units = "degC" ;
> 		rnnmm:units = "degC" ;
```

A few more things:
The variable name of the rx5day is incorrect in addition to its unit being incorrect. 
The units of the EHF HWA and HWM are degC^2, different to HWA and HWM based on the other definitions. I suggest just having a separate variable for each heatwave characteristic and definition combination so you can do this.

**Comment by heroldn** [comment]
Hi Tammas

There SHOULD be a fix for the units issue in the latest file, though I
didn't test it extensively. If you're climpact code has the following lines
then I know it doesn't work. If not, there's an update on git. This
basically stuffed up because the code was reading in all of the units, not
just the units for the indices being calculated. Thus because of indexing
the wrong units were assigned.

        units <- as.character(indexlist[match(indices,indexlist[,1]),2])
        desc <- as.character(indexlist[match(indices,indexlist[,1]),3])

Regarding heatwave units, thanks I'm aware, not sure how I'll do this as
it's a huge pain (and less efficiently coded) to separate those.

Cheers

Nick.

**Comment by tammasloughran** [comment]
OK just retried it, all good I think.
